version: '3'
services:
  captcha-proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    sysctls:
      - vm.overcommit_memory=1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]